# Generated by Django 3.2.17 on 2025-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('config_json', models.JSONField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
